### ISSUE TITLE
Add CoreNEURON-capable validation test.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/nsuite#14]
As we can only get spike times out of CoreNEURON, make a validation test that compares spike times.

Simplest would probably be to look at time to spike of a soma with exp2syn synapse activated by an artificially inserted spike. To extend it slightly, we could have two neurons and a connection; one is triggered artificially, which then triggers the next via the connection.

**Comment by halfflat** [comment]
Update: rc-exp2syn-spike test is implemented for NEURON and Arbor. CoreNEURON still pending.
Arbor does a bit better in this test than NEURON: its second spike is out by about _dt_; NEURON is out by about 3·_dt_

**Comment by bcumming** [comment]
I assume that Arbor's advantage is because Arbor:
  * does not round spike times to `dt` bins;
  * does not round event delivery times to `dt` bins.

It would be interesting to see what effect turning on event binning has in Arbor.

**Comment by halfflat** [comment]
And also, I believe, the event-driven integration dt.

**Comment by halfflat** [comment]
Updated test to take maximum error over a collection of cells connected to the first one via a quasirandom sequence of delays.
