### ISSUE TITLE
Standardise validation messages in `install-local.sh`

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/nsuite#34]
The installation of Arbor using `install-local.sh` outputs:
```
==  ARBOR: building benchmark models

==  ARBOR: busyring benchmark
==  ARBOR: cmake
==  ARBOR: make
==  ARBOR: install
==  ARBOR: saving environment
Configuring arbor-rc-exp2syn-spike.
Building arbor-rc-exp2syn-spike.
Configuring arbor-rc-expsyn.
Building arbor-rc-expsyn.

==  Installation finished
```

* Make the validation configure/build output consistent with the benchmarking
* Move it before saving the environment

**Comment by halfflat** [comment]
This is already covered in #15 — it's on my TODO!

**Comment by bcumming** [comment]
Sorry, I had a look and couldn't find the ticket that covered this.
