### ISSUE TITLE
Output during build is extremely low contrast

### ISSUE THREAD

**Issue by heplesser** [arbor-sim/nsuite#84]
The output provided during nsuite build is of so low contrast to be essentially unreadable/useless. Could you change to a slightly less faint gray?
![Screenshot 2019-09-06 at 11 11 33](https://user-images.githubusercontent.com/1059644/64416235-1ad02b00-d097-11e9-8fd8-8a60d00e28f3.png)

**Comment by halfflat** [comment]
Thanks for pointing this out! We've been living in a black-background bubble :)
I'll update the pretty-printing routines so that the output is legible across more terminal configurations.

**Comment by bcumming** [comment]
Hey HEP, if you checkout master, you should get more readable output now.

**Comment by heplesser** [comment]
Indeed, thanks for this amazingly fast fix!
